[package]
name = "out-glyph-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tpt-glyph-core = { path = "../crates/tpt-glyph-core" }
tpt-glyph-ps = { path = "../crates/tpt-glyph-ps" }
tpt-glyph-pdf = { path = "../crates/tpt-glyph-pdf" }

[[bin]]
name = "ps_interpreter"
path = "fuzz_targets/ps_interpreter.rs"
test = false
doc = false

[[bin]]
name = "pdf_content"
path = "fuzz_targets/pdf_content.rs"
test = false
doc = false

[workspace]
members = ["."]

[profile.release]
debug = 1
